### ISSUE TITLE
Magic Editor doesn't support code fences

### ISSUE THREAD

**Issue by MdoubleDash** [SO-Close-Vote-Reviewers/UserScripts#181] opened 2020-03-02 17:48 UTC
I have notices that Magic Editor removes multiple grave accents (code blocks) and multiple dollar signs (formula blocks). Moreover, at least for the formula blocks, it still capitalizes first words and applies other edits intended for simple text sections of the post.

**Comment by makyen** [comment] 2020-03-02 18:13
@MdoubleDash For the formula blocks problem, please open another issue. Also for that one, please provide at least one example post where it doesn't do what you're expecting. It would also help if you could link to some documentation which explained that format, as I don't see anything about it in [SO's Markdown formatting help](https://stackoverflow.com/editing-help) or in the [Official Markdown syntax guide](https://daringfireball.net/projects/markdown/syntax). Thanks.

**Comment by MdoubleDash** [comment] 2020-03-18 20:51
> 
> It would also help if you could link to some documentation which explained that format, as I don't see anything about it in [SO's Markdown formatting help](https://stackoverflow.com/editing-help) or in the [Official Markdown syntax guide](https://daringfireball.net/projects/markdown/syntax). Thanks.
> 

Formula block are not part of SO's markdown formatting but they are available on other SE communities like Math Overflow, Chemistry, etc.

Here's a snapshot of what I mean: https://math.stackexchange.com/posts/1138996/edit 

![image](https://user-images.githubusercontent.com/18401840/77006270-92c9b880-6938-11ea-8189-3598d50b80ad.png)

Let me know if you are planning to expand the support to other communities and I will post another issue if that's the case.

**Comment by makyen** [comment] 2020-03-18 21:37
@MdoubleDash We're happy to have support for things needed by other SE sites.

If there's a GitHub issue that describes what's desired, and points at some detailed information that specifies the format of the things which we should not change, then it's likely that it will be added. Basically, what would be needed is pointers to enough information such that the code could be written. Not having links to that information means that whoever is doing the work needs to go searching for it and *hope* that what they find actually describes what's really desired. Even an actual GitHub issue isn't required, but knowing enough about the specifications of what's desired really is needed. A GitHub issue of its own is just an easy way to track it and keep it in mind when looking at what needs to be/should be worked on.

If links to format specification/description information are available, then it's likely that implementing it would be in a similar time-frame as supporting code fences, because the effort should be in a similar section of the code (i.e. once having dived back into the code, it's relatively easy to implement something else that doesn't have a high cost, rather than postpone it to sometime when it would be necessary to come back up to speed on the code yet again).

So, yes, if it's something that's beneficial to have, then it would be good to have a GitHub issue for it.

BTW: I'm assuming that what you're wanting is for MagicEditor to avoid making changes within text that will be formatted by MathJax. From the documentation which I've seen ([1](https://math.stackexchange.com/editing-help#link-latex), [2](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)), that appears to be anything within `$...$` or `$$...$$`. The `$$...$$` case will be relatively rare to false-identify blocks, but the `$...$` demarcation could easily have significant false positives when using a naive identification (e.g. someone providing a list of prices in $, would look like multiple blocks of `$...$`). Is there something simple which further identifies the blocks? For instance, a lot of the examples appear to match the regex `/\$$?\s*\\[^$]*?\$$?/`, but it's not clear that the `$` *must* be followed by a `\`, with the possibility of intervening whitespace.

**Comment by makyen** [comment] 2020-07-03 22:16
Issue #187 was opened which concentrates on just the code fence problem. While the comments here are helpful, they're mostly about the formula block issue covered in #182. I'm going to close this issue as a duplicate of #187, because when reading these issues cold, it makes it clearer that there are two separate issues.

**Closed by makyen** 2020-07-03 22:16 UTC
Labels: bug, duplicate, enhancement, script: Magic™ Editor
