### ISSUE TITLE
cv-plz prompts for update after updating

### ISSUE THREAD

**Issue by mogsdad** [SO-Close-Vote-Reviewers/UserScripts#15] opened 2015-08-17 01:37 UTC
> There is a new version up. The new version contains the auto updater. If you could test it out for me by installing that version then change VERSION = '1.2' to VERSION = '1.1'. It should check once per day. If it says there is an update, try clicking cancel. Then select [Check for updates] from the menu. It should alert you of the update again. Then clicking [OK] should open a new tab to install the update. _/Tiny_

Performed the above test, starting with version 1.3. Performed multiple downgrade / upgrade cycles, and saw only one issue, the subject of this report.

 - Installed v 1.3, was previously running a v 1.0 from Tiny's own gh repo. Uninstalled the old version.
 - Loaded a question in another tab, validated that v1.3 was running by clicking <kbd>cv-pls</kbd> and observing the new 3-item menu.
 - In GreaseMonkey, edited then saved user script.

        // @version      1.1
        ...
        var CURRENT = '1.1';

 <sup><sub>Left GM editor open, because by re-saving the edited version I could perform "downgrades" for retesting.</sub></sup>

 - Back to question, reloaded page. Was prompted for update, as expected. Cancelled. 
 - Clicked <kbd>cv-pls</kbd> and selected _Check for updates_. Was alerted of update, as expected.
 - Updated, and confirmed update in GM.
 - Back to question, reloaded page. Was prompted for update. __<-- Suspected Bug__
 - Updated.

I have not been able to reproduce this again; I can downgrade & upgrade repeatedly now.

So, what happened? Theories...

- The "once per day" rule was in place for my first test, which explained the first notification when a question was opened, triggering the user script. Maybe cancelling that upgrade leaves an opening a the "once per day" check to run again.
- The first time I installed the new script, it didn't upgrade the previous version I had because it was from a different source. TM showed both as unique scripts, and I was able to remove the old one. Maybe there was some other interplay between them, perhaps via HTML5 storage.

Since the problem isn't persistently repetitive, it's a low impact issue.

**Comment by Tiny-Giant** [comment] 2015-08-17 03:40
Since I left that message in chat, I changed the updating system. 

I found the original method in the AutoComments script on stackapps. Basically, during a version check, it would actually load the script from the server and cancel the current script and compare the versions. This is very resource intensive, hence the once-a-day check. To compound on the issue, it interfered with the AJAX part of our script. GM_* functions were not available within the wrapper that was used.

It was a clever hack, but it didn't work for our situation. On the up-side of this, all I had to do was create a new version file in the repo, and I `@require` that into the script. This takes very little resources, and I could salvage the version comparison logic from the original method. Now there is no need for a once-a-day ,check so it will alert on any version increase.

That being said, it shouldn't tell you to update directly after updating, and the old script should not interfere with the new script. I'm going to try and reproduce this issue and see what I can find out. I'll report back when I know more.

**Comment by Tiny-Giant** [comment] 2015-08-17 23:38
I was able to reproduce this, showing the compared versions in the console showed a failed request for the version number, the returned error number happened to be larger than the current version number, so it would ask to update. This didn't happen very often, but it did happen. I've since modified the script to retrieve the version information using rawgit instead of linking directly to the github file. This seems to have solved the problem so I'm closing this issue.

**Closed by Tiny-Giant** 2015-08-17 23:38 UTC
Labels: script:SOCloseVoteRequestGenerator
